version: '3.7'
services:

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    image: voicemail-api:latest
    restart: on-failure
    user: www-data
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: voicemail
      DB_USERNAME: voicemail
      DB_PASSWORD: voicemail
    depends_on:
      - mysql
      - redis

#  worker:
#    image: voicemail-api:latest
#    command: "php artisan queue:work --sleep=3 --tries=3 --delay=30"
#    restart: on-failure
#    user: www-data
#    environment:
#      DB_CONNECTION: mysql
#      DB_HOST: mysql
#      DB_PORT: 3306
#      DB_DATABASE: voicemail
#      DB_USERNAME: voicemail
#      DB_PASSWORD: voicemail
#    depends_on:
#      - api

  cron:
    image: voicemail-api:latest
    command: "/usr/sbin/cron -f"
    restart: on-failure
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: voicemail
      DB_USERNAME: voicemail
      DB_PASSWORD: voicemail
    depends_on:
      - api

  redis:
    image: redis:alpine

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: voicemail
      MYSQL_DATABASE: voicemail
      MYSQL_USER: voicemail
      MYSQL_PASSWORD: voicemail
    ports:
      - '3306:3306'

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:8080'
    depends_on:
      - api
