version: '3.7'
services:

    voicemail_nginx:
        image: nginx
        container_name: voicemail_nginx
        restart: always
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/snippets/cors.conf:/etc/nginx/snippets/cors.conf
            - ./docker/nginx/voicemail.conf:/etc/nginx/conf.d/voicemail.conf
        networks:
            - web
            - default
        expose:
            - 80
        depends_on:
          - voicemail_api
        labels:
            - "traefik.docker.network=web"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:voicemail.nate.page"
            - "traefik.port=80"

    voicemail_api:
        build:
            context: ./
            dockerfile: ./docker/api/Dockerfile
        restart: always
        depends_on:
          - voicemail_mysql
        expose:
          - 9000

    voicemail_mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: voicemail
            MYSQL_DATABASE: voicemail
            MYSQL_USER: voicemail
            MYSQL_PASSWORD: voicemail
        ports:
            - '3306:3306'

networks:
    web:
        external: true
